/**
 * Code Viewer Component
 * 
 * Displays generated code using Monaco Editor (same editor as VS Code).
 * Provides syntax highlighting, copy functionality, and basic editing.
 */

import { useState, useRef } from 'react';
import Editor from '@monaco-editor/react';
import { logger } from '../utils/logger.js';
import HelpButton from './HelpButton.jsx';

function CodeViewer({ 
  code = '', 
  language = 'javascript',
  title = 'Generated Code',
  readOnly = true,
  onChange,
  height = '300px',
  showCopy = true,
  showDownload = true,
}) {
  const [isCopied, setIsCopied] = useState(false);
  const editorRef = useRef(null);

  const handleEditorMount = (editor) => {
    editorRef.current = editor;
    logger.ui('editor-mounted', { language, readOnly });
  };

  const handleCopy = async () => {
    if (!code) return;
    
    try {
      await navigator.clipboard.writeText(code);
      setIsCopied(true);
      logger.ui('code-copied', { length: code.length });
      
      setTimeout(() => setIsCopied(false), 2000);
    } catch (error) {
      logger.error('CodeViewer', error);
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = code;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2000);
    }
  };

  const handleDownload = () => {
    if (!code) return;
    
    const blob = new Blob([code], { type: 'text/javascript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'generated-code.js';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    logger.ui('code-downloaded', { length: code.length });
  };

  const handleEditorChange = (value) => {
    if (onChange) {
      onChange(value);
    }
  };

  const lineCount = code ? code.split('\n').length : 0;
  const charCount = code ? code.length : 0;

  const helpContent = (
    <div>
      <h4 style={{ marginTop: 0, marginBottom: '8px', fontSize: '15px', fontWeight: '700', color: '#111827' }}>What is this panel?</h4>
      <p style={{ marginTop: 0, marginBottom: '12px', color: '#1f2937' }}>The Code Viewer displays generated code using Monaco Editor (the same editor used in VS Code).</p>
      
      <h4 style={{ marginTop: '12px', marginBottom: '8px', fontSize: '15px', fontWeight: '700', color: '#111827' }}>Features:</h4>
      <ul style={{ marginTop: 0, marginBottom: '12px', paddingLeft: '20px', color: '#1f2937' }}>
        <li style={{ marginBottom: '6px' }}><strong style={{ color: '#111827', fontWeight: '600' }}>Real-time streaming:</strong> Code appears as it's generated by Ollama</li>
        <li style={{ marginBottom: '6px' }}><strong style={{ color: '#111827', fontWeight: '600' }}>Syntax highlighting:</strong> JavaScript syntax is highlighted automatically</li>
        <li style={{ marginBottom: '6px' }}><strong style={{ color: '#111827', fontWeight: '600' }}>Copy to clipboard:</strong> Click the copy button to copy code</li>
        <li style={{ marginBottom: '6px' }}><strong style={{ color: '#111827', fontWeight: '600' }}>Read-only by default:</strong> Code is displayed read-only, but you can edit if needed</li>
      </ul>
      
      <h4 style={{ marginTop: '12px', marginBottom: '8px', fontSize: '15px', fontWeight: '700', color: '#111827' }}>Files involved:</h4>
      <ul style={{ marginTop: 0, marginBottom: '12px', paddingLeft: '20px', color: '#1f2937' }}>
        <li style={{ marginBottom: '6px' }}><code style={{ backgroundColor: '#f3f4f6', color: '#111827', padding: '2px 6px', borderRadius: '4px', fontSize: '13px', fontFamily: 'monospace', border: '1px solid #d1d5db' }}>src/components/CodeViewer.jsx</code> - This component</li>
        <li style={{ marginBottom: '6px' }}><code style={{ backgroundColor: '#f3f4f6', color: '#111827', padding: '2px 6px', borderRadius: '4px', fontSize: '13px', fontFamily: 'monospace', border: '1px solid #d1d5db' }}>@monaco-editor/react</code> - Monaco Editor React wrapper</li>
        <li style={{ marginBottom: '6px' }}><code style={{ backgroundColor: '#f3f4f6', color: '#111827', padding: '2px 6px', borderRadius: '4px', fontSize: '13px', fontFamily: 'monospace', border: '1px solid #d1d5db' }}>src/utils/codeParser.js</code> - Extracts code from LLM markdown responses</li>
        <li style={{ marginBottom: '6px' }}><code style={{ backgroundColor: '#f3f4f6', color: '#111827', padding: '2px 6px', borderRadius: '4px', fontSize: '13px', fontFamily: 'monospace', border: '1px solid #d1d5db' }}>src/hooks/useOllama.js</code> - Provides streaming code updates</li>
      </ul>
      
      <h4 style={{ marginTop: '12px', marginBottom: '8px', fontSize: '15px', fontWeight: '700', color: '#111827' }}>How it works:</h4>
      <p style={{ marginTop: 0, marginBottom: 0, color: '#1f2937' }}>When code is generated, it streams in real-time from Ollama. The code is extracted from markdown code blocks and displayed here. You can copy it or edit it directly.</p>
    </div>
  );

  return (
    <div style={styles.container}>
      {/* Header */}
      <div style={styles.header}>
        <div style={styles.titleArea}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <span style={styles.title}>{title}</span>
            <HelpButton content={helpContent} title="Code Viewer Help" />
          </div>
          {code && (
            <span style={styles.stats}>
              {lineCount} line{lineCount !== 1 ? 's' : ''} • {charCount} char{charCount !== 1 ? 's' : ''}
            </span>
          )}
        </div>
        
        <div style={styles.actions}>
          {showCopy && code && (
            <button
              onClick={handleCopy}
              style={styles.actionButton}
              title="Copy to clipboard"
            >
              {isCopied ? '✓ Copied!' : '📋 Copy'}
            </button>
          )}
          {showDownload && code && (
            <button
              onClick={handleDownload}
              style={styles.actionButton}
              title="Download as .js file"
            >
              ⬇️ Download
            </button>
          )}
        </div>
      </div>

      {/* Editor */}
      <div style={styles.editorWrapper}>
        {code ? (
          <Editor
            height={height}
            language={language}
            value={code}
            theme="vs-dark"
            onMount={handleEditorMount}
            onChange={handleEditorChange}
            options={{
              readOnly,
              minimap: { enabled: false },
              fontSize: 14,
              fontFamily: "'Fira Code', 'Consolas', 'Monaco', monospace",
              lineNumbers: 'on',
              scrollBeyondLastLine: false,
              automaticLayout: true,
              tabSize: 2,
              wordWrap: 'on',
              padding: { top: 12, bottom: 12 },
              renderLineHighlight: readOnly ? 'none' : 'line',
              cursorStyle: readOnly ? 'line-thin' : 'line',
            }}
          />
        ) : (
          <div style={styles.placeholder}>
            <span style={styles.placeholderIcon}>📝</span>
            <span style={styles.placeholderText}>
              Generated code will appear here
            </span>
            <span style={styles.placeholderHint}>
              Enter a goal and click "Generate Code" to start
            </span>
          </div>
        )}
      </div>

      {/* Footer info */}
      {code && (
        <div style={styles.footer}>
          <span style={styles.footerText}>
            💡 {readOnly ? 'Read-only view' : 'You can edit this code'}
          </span>
        </div>
      )}
    </div>
  );
}

const styles = {
  container: {
    backgroundColor: '#16213e',
    borderRadius: '12px',
    border: '1px solid #2a2a4a',
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 16px',
    borderBottom: '1px solid #2a2a4a',
    backgroundColor: '#0d1117',
  },
  titleArea: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  title: {
    fontWeight: '500',
    color: '#eaeaea',
    fontSize: '14px',
  },
  stats: {
    color: '#6b7280',
    fontSize: '12px',
  },
  actions: {
    display: 'flex',
    gap: '8px',
  },
  actionButton: {
    padding: '6px 12px',
    backgroundColor: 'transparent',
    color: '#a0a0a0',
    border: '1px solid #2a2a4a',
    borderRadius: '6px',
    fontSize: '12px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  editorWrapper: {
    backgroundColor: '#0d1117',
  },
  placeholder: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '60px 20px',
    gap: '12px',
  },
  placeholderIcon: {
    fontSize: '48px',
    opacity: 0.5,
  },
  placeholderText: {
    color: '#a0a0a0',
    fontSize: '16px',
  },
  placeholderHint: {
    color: '#6b7280',
    fontSize: '14px',
  },
  footer: {
    padding: '8px 16px',
    borderTop: '1px solid #2a2a4a',
    backgroundColor: '#0d1117',
  },
  footerText: {
    color: '#6b7280',
    fontSize: '12px',
  },
};

export default CodeViewer;
